/** アプリ用語の固定訳。完全一致を優先し、残りは機械翻訳。 */

var GLOSSARY_VI = {
  "(テーマ未設定)": "(Chưa đặt chủ đề)",
  "10%　テーマ設定済み": "10% — Đã đặt chủ đề",
  "100%　完了": "100% — Hoàn tất",
  "20%　ゴール設定済み": "20% — Đã đặt mục tiêu",
  "30%　今の状況設定（SWOTマトリクス完成）": "30% — Đã thiết lập tình hình hiện tại (hoàn thành ma trận SWOT)",
  "40%　方策決定済み": "40% — Đã quyết định phương án",
  "50%　最初の一歩設定済み": "50% — Đã thiết lập bước đầu tiên",
  "60%　宣言終了": "60% — Đã hoàn tất tuyên bố",
  "70%　振り返り　1回実施": "70% — Đã nhìn lại 1 lần",
  "80%　振り返り　2回実施": "80% — Đã nhìn lại 2 lần",
  "90%　振り返り　3回以上実施": "90% — Đã nhìn lại từ 3 lần trở lên",
  "AIが考えた10個の最初の一歩": "10 bước đầu tiên từ AI",
  "AIが考えた5つの方策": "5 phương án từ AI",
  "AIに再度相談する": "Hỏi AI lại",
  "AIに方策を相談する": "Hỏi AI về phương án",
  "AIの回答をコピーしたら、この画面に戻って\n下のボタンをタップしてください。": "Sau khi sao chép câu trả lời của AI, hãy quay lại màn hình này\nvà nhấn nút bên dưới.",
  "AIの提案にない、独自の方策があれば書く": "Nếu bạn có phương án riêng không nằm trong gợi ý của AI, hãy viết ở đây",
  "AIの提案にない、独自の最初の一歩があれば書く": "Nếu bạn có bước đầu tiên riêng không nằm trong gợi ý của AI, hãy viết ở đây",
  "Apple プライバシーポリシー": "Chính sách quyền riêng tư của Apple",
  "Chromeでの回答を確認してください": "Vui lòng kiểm tra câu trả lời trên Chrome",
  "Chromeを開いています…": "Đang mở Chrome…",
  "Chromeを開き直す": "Mở lại Chrome",
  "Chromeを開けませんでした": "Không thể mở Chrome",
  "Google AIによる方策提案": "Đề xuất phương án qua Google AI",
  "Google AIによる最初の一歩提案": "Đề xuất bước đầu tiên qua Google AI",
  "Google プライバシーポリシー": "Chính sách quyền riêng tư của Google",
  "JSONを取り込む": "Nhập JSON",
  "JSONバックアップ": "Sao lưu JSON",
  "SWOTマトリクス": "Ma trận SWOT",
  "iCloud同期": "Đồng bộ iCloud",
  "iCloud同期_アップロード完了": "Đã tải lên iCloud",
  "iCloud同期_エラー": "Đồng bộ thất bại",
  "iCloud同期_エラー_マージ失敗": "Không thể áp dụng dữ liệu đã tải xuống.",
  "iCloud同期_エラー_不正な応答": "Nhận được phản hồi không mong muốn từ iCloud.",
  "iCloud同期_エラー_容量超過": "Dữ liệu của bạn (%@ MB) vượt quá giới hạn đồng bộ iCloud (1 MB).",
  "iCloud同期_エラー_未検出": "Không tìm thấy tính năng đồng bộ iCloud. Vui lòng khởi động lại ứng dụng.",
  "iCloud同期_エラー_案件未読込": "Dữ liệu án chưa tải xong.",
  "iCloud同期_クラウドコピーを削除": "Xóa bản sao đám mây iCloud",
  "iCloud同期_クラウドコピーを削除しますか？": "Xóa bản sao iCloud?",
  "iCloud同期_クラウドコピー削除失敗": "Không thể xóa. Hãy kiểm tra iCloud và thử lại.",
  "iCloud同期_クラウドコピー削除完了": "Đã xóa bản sao iCloud.",
  "iCloud同期_クラウドコピー削除確認": "Thao tác này xóa dữ liệu án osmJiritsu và thời điểm đồng bộ khỏi iCloud KVS, nhưng không xóa án trên thiết bị.",
  "iCloud同期_ダウンロード完了": "Đã tải xuống từ iCloud",
  "iCloud同期_フッター": "Chủ đề, mục tiêu, SWOT, phương án, bước đầu tiên, tuyên bố và các lần nhìn lại của án được lưu trong iCloud Key-Value Storage và chia sẻ giữa các thiết bị cùng tài khoản iCloud.",
  "iCloud同期_今すぐ同期": "Đồng bộ ngay",
  "iCloud同期_利用不可": "iCloud hiện không khả dụng. Vui lòng đăng nhập iCloud trong Cài đặt.",
  "iCloud同期_最終同期": "Đồng bộ lần cuối",
  "iCloud同期_有効化フッター": "Khi bật, dữ liệu án được đồng bộ giữa các thiết bị đăng nhập cùng tài khoản iCloud.",
  "iCloud同期_未同期": "Chưa đồng bộ",
  "iCloud同期_相対時刻_今": "Vừa xong",
  "iCloud同期_相対時刻_分": "%lld phút trước",
  "iCloud同期_相対時刻_日": "%lld ngày trước",
  "iCloud同期_相対時刻_時間": "%lld giờ trước",
  "― 伊藤守「リーダーになる人ならない人」": "― Itō Mamoru, \"Rīdā ni Naru Hito, Naranai Hito\" (Người trở thành lãnh đạo, người thì không)",
  "❌ 本人の興味に依存するため即効性がない": "❌ Phụ thuộc vào sở thích cá nhân nên không có hiệu quả tức thì",
  "❌ 誰にでも同じように適用することは困難": "❌ Khó áp dụng giống nhau cho mọi người",
  "⭕️ モチベーションが長持ちする": "⭕️ Động lực kéo dài lâu",
  "「在りたい姿」と「在りたくない姿」、両方の向きから考えてみましょう。": "Hãy cùng suy nghĩ theo cả hai hướng: \"hình ảnh bạn muốn trở thành\" và \"hình ảnh bạn không muốn trở thành\".",
  "「採用済／未採用」はタップで切り替えられます。文言を直したいときは案を長押しで編集できます。": "Chạm để chuyển giữa Đã áp dụng và Chưa áp dụng. Nhấn giữ một phương án để sửa nội dung.",
  "あとで（履歴に戻る）": "Để sau (quay lại lịch sử)",
  "あなたの方策": "Phương án của bạn",
  "あなたの最初の一歩": "Bước đầu tiên của bạn",
  "お気に入りに追加": "Thêm vào yêu thích",
  "お気に入り解除": "Bỏ khỏi yêu thích",
  "ここに置く": "Thả vào đây",
  "この分析を削除しますか？": "Xóa phân tích này?",
  "この振り返りを削除しますか？": "Xóa lần nhìn lại này?",
  "これが実現すれば十分、と言える理想の姿（充分条件）": "Trạng thái lý tưởng mà nếu đạt được thì coi như đủ (điều kiện đủ)",
  "これだけは避けたい、という最低ライン（必要条件）": "Ranh giới tối thiểu bạn muốn tránh (điều kiện cần)",
  "これって、良いこと？ 気になること？": "Đây là điều tốt, hay điều khiến bạn lo lắng?",
  "すべてのデータを初期化": "Đặt lại toàn bộ dữ liệu",
  "すべてのデータを削除": "Xóa toàn bộ dữ liệu",
  "その他": "Khác",
  "それって、自分次第で変えられる？": "Điều đó bạn có thể tự thay đổi được không?",
  "それでは始めましょう": "Vậy thì, hãy bắt đầu",
  "つまり「唱って躍れる」とは「周りを引っ張って、元気に前に進める」「自分の考えを話して、みんなと共有できる」ことである。": "Nói cách khác, \"唱って躍れる\" (xướng lên và nhảy múa) nghĩa là \"dẫn dắt mọi người xung quanh, tiến về phía trước một cách đầy nhiệt huyết\" và \"nói lên suy nghĩ của bản thân, chia sẻ cùng mọi người\".",
  "できない理由だけで、どうすればできるか？がない": "Chỉ nêu lý do không làm được, không nghĩ cách để làm được",
  "どうだった？": "Mọi việc thế nào?",
  "どの枠に入れますか？": "Cho vào ô nào?",
  "なし": "Không có",
  "はじめからやり直す": "Bắt đầu lại từ đầu",
  "はじめる": "Bắt đầu",
  "まずテーマを決めよう": "Trước tiên, hãy chọn chủ đề.",
  "まとめを共有": "Chia sẻ tóm tắt",
  "まわりの状況": "Hoàn cảnh xung quanh",
  "もう一度Chromeを開く": "Mở lại Chrome",
  "もう一度試す": "Thử lại",
  "もう一度貼り付ける": "Dán lại",
  "やっぱりやらない": "Thôi, không làm nữa",
  "アイデアを出してみる": "Bắt đầu đưa ra ý tưởng",
  "アプリの表示言語を変更できます。": "Bạn có thể thay đổi ngôn ngữ hiển thị của ứng dụng.",
  "インポート": "Nhập",
  "エクスポート": "Xuất",
  "エクスポートする": "Xuất",
  "エクスポートできる分析がまだありません": "Chưa có gì để xuất",
  "キャンセル": "Hủy",
  "キーワード": "Từ khóa",
  "クリップボードが空でした。Chromeで回答をコピーしてから、もう一度貼り付けてみてください。": "Bảng nhớ tạm trống. Hãy sao chép câu trả lời trên Chrome rồi thử dán lại.",
  "ゴールと今の状況の差を無くすために、自分で考えて行動すること": "Tự suy nghĩ và hành động để thu hẹp khoảng cách giữa mục tiêu và tình trạng hiện tại",
  "周りと繋がっているか？": "Bạn có thể chia sẻ mục tiêu không?",
  "ゴールを教えてください": "Hãy cho chúng tôi biết mục tiêu của bạn",
  "ゴールを考える": "Nghĩ về mục tiêu",
  "スタートアップ画面": "Màn hình khởi động",
  "タップで今の状況を編集": "Chạm để sửa tình hình hiện tại",
  "タップまたは長押しで編集": "Chạm hoặc nhấn giữ để sửa",
  "ダッシュボードの全項目": "Toàn bộ mục trên bảng điều khiển",
  "ダッシュボードへ": "Mở bảng điều khiển",
  "テーマ": "Chủ đề",
  "テーマとゴール（在りたい姿／在りたくない姿）を決める": "Đặt chủ đề và mục tiêu (trạng thái mong muốn / không mong muốn)",
  "テーマを編集": "Chỉnh sửa chủ đề",
  "データ": "Dữ liệu",
  "プライバシー": "Quyền riêng tư",
  "プライバシー_ポリシー本文_詳細": "Chi tiết về gửi dữ liệu ra ngoài, thời gian lưu giữ và cách xóa.",
  "プライバシー_保存詳細": "Chủ đề, mục tiêu, phân tích SWOT, phương án, bước đầu tiên, tuyên bố, nhìn lại, thứ tự dự án, ngôn ngữ hiển thị và cài đặt màn hình bắt đầu được lưu trong cơ sở dữ liệu Hive cục bộ trên thiết bị. Không đồng bộ đám mây.",
  "プライバシー_保持削除詳細": "Dữ liệu đã lưu được giữ đến khi bạn xóa từng mục hoặc chọn Xóa toàn bộ dữ liệu. Dữ liệu đã gửi đến Google được lưu giữ và xóa theo chính sách của Google, và không thể xóa từ ứng dụng này. Bản sao lưu JSON đã lưu ở ứng dụng khác cũng không thể xóa bởi ứng dụng này.",
  "プライバシー_削除確認": "Xóa lịch sử phân tích và cài đặt Hive cùng các tệp sao lưu tạm thời? Không thể hoàn tác.",
  "プライバシー_外部送信": "Bên nhận, dữ liệu và mục đích",
  "プライバシー_方策説明": "Nếu bạn yêu cầu đề xuất phương án, chủ đề, trạng thái mong muốn, trạng thái không mong muốn và toàn bộ SWOT (điểm mạnh, điểm yếu, cơ hội, mối đe dọa) sẽ được gửi đến Google Search (chế độ AI) do Google LLC cung cấp. Mục đích là nhận đề xuất phương án tham khảo. Ứng dụng hỏi sự đồng ý cho mỗi lần gửi. Áp dụng điều khoản và chính sách quyền riêng tư của Google.",
  "プライバシー_最初の一歩説明": "Nếu bạn yêu cầu đề xuất bước đầu tiên, chủ đề, trạng thái mong muốn và phương án đã chọn sẽ được gửi đến Google Search (chế độ AI) do Google LLC cung cấp. Mục đích là nhận đề xuất bước đầu tiên tham khảo. Ứng dụng hỏi sự đồng ý cho mỗi lần gửi. Áp dụng điều khoản và chính sách quyền riêng tư của Google.",
  "プライバシー_端末保存": "Lưu trữ trên thiết bị",
  "プライバシー_関連ポリシー_詳細": "Chính sách của Google áp dụng cho nội dung gửi đến Google Search (chế độ AI). Điều khoản của Apple có thể áp dụng cho phân phối App Store và sao lưu thiết bị.",
  "プライバシーとデータ": "Quyền riêng tư & Dữ liệu",
  "プライバシーポリシー": "Chính sách quyền riêng tư",
  "ヘルプ": "Trợ giúp",
  "ホーム": "Trang chủ",
  "ボタン長押しで\n操作方法を確認できます": " để xem cách sử dụng",
  "マトリクスを確認する": "Xem ma trận",
  "ユーザーズマニュアル": "Hướng dẫn sử dụng",
  "リターン": "Quay lại",
  "一旦休む": "Tạm nghỉ",
  "一見クールでカッコよく見えたりする。的を射てるし。周囲を白けさせるパワー大。口癖は「でもさ...」": "Thoạt nhìn có vẻ ngầu và có lý. Nhưng lại rất dễ làm nguội lạnh không khí xung quanh. Câu cửa miệng là \"nhưng mà...\"",
  "上司や仲間にそのまま送れます。": "Sẵn sàng gửi cho cấp trên hoặc đồng nghiệp.",
  "上司や仲間にそのまま送れる、ひとことにしましょう。": "Hãy viết thành một câu có thể gửi ngay cho cấp trên hoặc đồng nghiệp.",
  "不安・課題に感じる": "Cảm thấy bất an / là vấn đề",
  "不平、不満ばっかり": "Toàn than phiền, bất mãn",
  "主導権は自分にあるのだと意識すること": "Ý thức rằng quyền chủ động nằm ở bạn",
  "今の状況": "Tình hình hiện tại",
  "他人から言われる前に動く": "Hành động trước khi người khác nhắc bạn",
  "休憩中": "Đang tạm nghỉ",
  "作成中": "Đang chuẩn bị",
  "作成中_ホームで一覧": "Dùng nút Home để về danh sách dự án",
  "例）妥協して、納得感のないまま転職すること": "VD: Thỏa hiệp và chuyển việc mà không thấy thỏa mãn",
  "例）新しいキャリアについて": "VD: Về sự nghiệp mới",
  "例）自分の強みを活かして、納得感のある転職をしたい": "VD: Tôi muốn chuyển việc theo cách phát huy thế mạnh của mình",
  "保存": "Lưu",
  "備考": "Ghi chú",
  "備考を入力…": "Nhập ghi chú…",
  "元に戻すことはできません。": "Không thể hoàn tác.",
  "全部答えられました！": "Bạn đã trả lời hết!",
  "共有": "Chia sẻ",
  "共有_テキスト説明": "Chia sẻ dạng văn bản (email, ứng dụng nhắn tin, v.v.). Tóm tắt là kế hoạch ngắn; báo cáo đầy đủ là mọi mục trên bảng điều khiển. Sao lưu JSON nằm trong menu Dữ liệu ở màn hình chính.",
  "共有_要報説明": "Dạng ngắn (chủ đề, mục tiêu, phương sách, bước đầu, tuyên bố). Giống bản tóm tắt sau Stage1.",
  "共有_詳報説明": "Mọi mục trên bảng điều khiển (SWOT, nhìn lại, hạn, v.v.). Phù hợp chia sẻ tiến độ hàng ngày.",
  "共有する": "Chia sẻ",
  "共有形式を選んでください": "Chọn định dạng chia sẻ",
  "内容を編集": "Sửa nội dung",
  "内発か？外発か？": "Nội tại hay bên ngoài?",
  "内発と外発は対立するものではなく組み合わせもの。外発をきっかけに始めて、その内、それ自体が楽しくなる...（エンハンシング効果）。": "Động lực nội tại và bên ngoài không đối lập mà có thể kết hợp với nhau. Có thể bắt đầu nhờ một tác nhân bên ngoài, rồi dần dần chính hoạt động đó trở nên thú vị... (hiệu ứng khuếch đại).",
  "内発的動機づけ": "Động lực nội tại",
  "分析結果": "Kết quả phân tích",
  "初期化": "Đặt lại",
  "初期化しました": "Đã đặt lại",
  "初期化の説明": "Xóa mọi dữ liệu và cài đặt cục bộ, khôi phục trạng thái ban đầu. Không thể hoàn tác.",
  "削除": "Xóa",
  "削除する": "Xóa",
  "動機づけマトリクス": "Ma trận động lực",
  "各画面の": "Trên mỗi màn hình, nhấn giữ nút ",
  "同意してGoogleへ送信": "Đồng ý và gửi đến Google",
  "周囲からサポートを得る": "Nhận được sự hỗ trợ từ xung quanh",
  "唱って躍れる": "唱って躍れる\nutatte odoreru",
  "唱義：人に先立って正しい道をとなえる": "唱義: đi trước người khác để xướng lên con đường đúng đắn",
  "唱（ショウ）": "Xướng (唱)",
  "図解で画面ごとの使い方を見る": "Xem cách dùng từng màn hình bằng hình",
  "在りたい姿": "Hình ảnh mong muốn",
  "在りたくない姿": "Hình ảnh bạn không muốn trở thành",
  "報酬、評価、昇進、あるいは罰則や叱責といった「外部からの刺激」をきっかけとして行動を促すこと。": "Thúc đẩy hành động thông qua các \"kích thích từ bên ngoài\" như phần thưởng, đánh giá, thăng chức, hoặc hình phạt và khiển trách.",
  "壁打ちメモ": "Ghi chú brainstorm",
  "外発的動機づけ": "Động lực bên ngoài",
  "完了": "Hoàn tất",
  "実はこれ、SWOT分析になっています。\n出来上がったマトリクスを見てみましょう。": "Thực ra đây chính là một phân tích SWOT.\nHãy cùng xem ma trận đã hoàn thành.",
  "実施中": "Đang thực hiện",
  "実行のステップを細かくして達成感を感じやすくすること。": "Chia nhỏ các bước thực hiện để dễ cảm nhận thành tựu.",
  "宣言文": "Tuyên bố",
  "宣言文を確認する": "Xem lại tuyên bố",
  "宣言文を編集": "Sửa tuyên bố",
  "小さなくるくる": "小さなくるくる\nchiisana kurukuru",
  "履歴に戻る": "Quay lại lịch sử",
  "弱み": "Điểm yếu",
  "強み": "Điểm mạnh",
  "思いついたことを入力…": "Nhập điều bạn nghĩ đến…",
  "思いつくままに、どんどん追加しよう": "Hãy thêm bất cứ điều gì nghĩ đến, liên tục",
  "感じたこと、気づいたことを自由に書いてみましょう": "Hãy viết tự do về điều bạn cảm nhận hoặc nhận ra",
  "戻す": "Hoàn tác",
  "戻る": "Quay lại",
  "振り返り": "Nhìn lại",
  "振り返りを編集": "Sửa nhìn lại",
  "振り返り回数": "Số lần nhìn lại",
  "振り返り履歴": "Lịch sử nhìn lại",
  "採用済": "Đã áp dụng",
  "操作マニュアル": "Hướng dẫn sử dụng",
  "操作方法": "Cách sử dụng",
  "操作方法_ダッシュボード": "1️⃣ Xem/mở: chạm ▶︎\n2️⃣ Xóa án: chạm 🗑️ hoặc vuốt sang trái\n3️⃣ Sửa chủ đề: chạm 🖊️\n4️⃣ Thêm vào yêu thích: chạm ☆\n5️⃣ Thêm mới: chạm ＋",
  "操作方法_宣言": "1️⃣ Sửa: chạm vào mục",
  "操作方法_方策最初の一歩": "1️⃣ Sửa: nhấn giữ mục",
  "文言を編集": "Sửa nội dung",
  "新しいテーマに取り組む": "Bắt đầu chủ đề mới",
  "新規追加": "Thêm mới",
  "方策": "Phương án",
  "方策の粒度を細かくすること": "Chia nhỏ phương án thành các bước",
  "方策や行動を決めるとき、この3つを満たしているか振り返ってみましょう。": "Khi quyết định phương án hoặc hành động, hãy kiểm tra xem đã đáp ứng cả 3 điều này chưa.",
  "方策を取り消しますか？": "Hủy bỏ phương án này?",
  "方策を変更する": "Thay đổi phương án",
  "方策を決めた": "Đã quyết định phương án",
  "方策を決める": "Quyết định phương án",
  "方策を編集": "Sửa phương án",
  "方策を編集する": "Chỉnh sửa phương án",
  "方策を考える際、動機づけマトリクスを意識すると良い。": "Khi suy nghĩ về phương án, hãy để ý đến ma trận động lực.",
  "方策を見直す": "Xem lại phương án",
  "方策を読み取れませんでした。Chromeの回答全体をコピーしてから、もう一度貼り付けてみてください。": "Không thể đọc được phương án. Hãy sao chép toàn bộ câu trả lời từ Chrome rồi thử dán lại.",
  "昌には、盛んで明るいとか、美しいことばという意味があり、それと口にすることから、唱は、うたう、となえるの意味を表す。また、昌の音は、高く上げるという意味を含むから、唱は、声を高くあげること、あるいは、「人より先に大声を上げてリードする」ことである。": "昌 mang ý nghĩa \"hưng thịnh, tươi sáng\" hay \"lời nói đẹp\"; kết hợp với 口 (miệng, cất tiếng), 唱 mang nghĩa \"hát\", \"xướng lên\". Âm của 昌 còn hàm ý \"nâng cao lên\", nên 唱 còn có nghĩa \"cất cao giọng nói\", hay \"dẫn đầu bằng cách lên tiếng lớn trước người khác\".",
  "最初の一歩": "Bước đầu tiên",
  "最初の一歩を取り消しますか？": "Hủy bỏ bước đầu tiên này?",
  "最初の一歩を宣言し、振り返りながら進める": "Tuyên bố bước đầu tiên, rồi tiến lên kèm nhìn lại",
  "最初の一歩を決めた": "Đã quyết định bước đầu tiên",
  "最初の一歩を決める": "Quyết định bước đầu tiên",
  "最初の一歩を編集": "Sửa bước đầu tiên",
  "最初の一歩を編集する": "Chỉnh sửa bước đầu tiên",
  "最初の一歩を見直す": "Xem lại bước đầu tiên",
  "最初の一歩を読み取れませんでした。Chromeの回答全体をコピーしてから、もう一度貼り付けてみてください。": "Không thể đọc được bước đầu tiên. Hãy sao chép toàn bộ câu trả lời từ Chrome rồi thử dán lại.",
  "最終更新日": "Cập nhật lần cuối",
  "期限": "Hạn chót",
  "期限を設定": "Đặt hạn chót",
  "未採用": "Chưa áp dụng",
  "未設定": "Chưa đặt",
  "本当に初期化しますか？": "Đặt lại toàn bộ?",
  "案件があっても、起動時はスタート画面から始めます。": "Luôn bắt đầu từ màn hình bắt đầu khi khởi động, kể cả khi đã có dự án.",
  "案内に従って操作": "Làm theo hướng dẫn trên màn hình",
  "機会": "Cơ hội",
  "次はどうする？": "Tiếp theo bạn muốn làm gì?",
  "次回から表示しない": "Không hiện lại",
  "気になること": "Điều lo lắng",
  "決めた方策を、3つの要素から見直してみましょう。": "Hãy cùng xem lại phương án đã quyết định theo 3 yếu tố.",
  "決定": "Xác nhận",
  "無感動、無関心": "Thờ ơ, không quan tâm",
  "現況を変更": "Thay đổi tình trạng",
  "現状を整理し、SWOTから方策を自分で決める": "Sắp xếp hiện trạng, rồi tự quyết định phương án từ SWOT",
  "環境や他人に左右される": "Bị ảnh hưởng bởi môi trường hoặc người khác",
  "登録日": "Ngày đăng ký",
  "短い形式（テーマ・ゴール・方策・最初の一歩・宣言文）": "Dạng ngắn (chủ đề, mục tiêu, phương án, bước đầu, tuyên bố)",
  "端末内のアプリデータを削除しました": "Đã xóa dữ liệu ứng dụng trên thiết bị",
  "納得した": "Tôi đã hài lòng",
  "純粋に人を喜ばせたくて仕事に取り組む。": "Bắt tay vào công việc chỉ vì muốn làm người khác vui.",
  "成果が分かりやすいか？": "Kết quả có dễ nhận biết không?",
  "結果を見える化して視覚的に成果を実感すること": "Trực quan hóa kết quả để cảm nhận rõ thành quả",
  "続ける": "Tiếp tục",
  "編集": "Chỉnh sửa",
  "翟には高く抜き出る意味がある。躍は「すばやくおどりあがる」ことである。": "翟 mang ý nghĩa \"vươn cao, nổi bật\". 躍 là \"nhảy vọt lên nhanh chóng\".",
  "脅威": "Nguy cơ",
  "自信がある・嬉しい": "Tự tin / vui mừng",
  "自分で決められるか？": "Bạn có thể tự quyết định không?",
  "自分の内面的な興味・関心、探究心、楽しさなどが原動力となる状態。": "Trạng thái được thúc đẩy bởi sự quan tâm, tò mò, hay niềm vui nội tại của chính bản thân.",
  "自分以外の何ものにも依存しない状態。": "Trạng thái không phụ thuộc vào bất cứ điều gì ngoài bản thân.",
  "自分次第": "Tùy vào bản thân",
  "自律できていない人にありがちな行動": "Hành vi thường gặp ở người chưa có Jiritsu",
  "自律とは": "Jiritsu là gì?",
  "自律とは、ゴールと今の状況の差を無くすために、自分で考えて行動することです。": "Jiritsu là tự suy nghĩ và hành động để thu hẹp khoảng cách giữa mục tiêu và tình trạng hiện tại.",
  "自律の3要素": "3 yếu tố của Jiritsu",
  "自律の定義": "Định nghĩa của Jiritsu",
  "内発度をチェックする": "Kiểm tra Jiritsu",
  "内発度チェック": "Kiểm tra Jiritsu",
  "自律計画ができました": "Kế hoạch Jiritsu của bạn đã sẵn sàng",
  "自立できていない、依存している人は、自分のうまく行かない状態の責任や自分の感情、思考の原因すら周りの人や環境のせいにする。": "Người chưa tự lập, còn phụ thuộc, thường đổ lỗi cho người xung quanh hay hoàn cảnh — kể cả về những thất bại, cảm xúc và suy nghĩ của chính mình.",
  "自立には経済的自立、行動的自立、精神的自立があり、いずれも自律と密接に関係している（自律している人は自立できる）。": "Tự lập gồm ba mặt: tự lập về kinh tế, tự lập về hành động, và tự lập về tinh thần — cả ba đều liên quan mật thiết đến Jiritsu (người có Jiritsu thì có thể tự lập).",
  "興味のある分野について自主的に深く調べる。": "Tự mình tìm hiểu sâu về một lĩnh vực mà bạn quan tâm.",
  "良いこと": "Điều tốt",
  "行動すること自体が目的となるため、高い集中力が発揮され、質が高く、自発的な行動を長く続けやすい。": "Vì bản thân hành động đã là mục đích, nên dễ đạt được sự tập trung cao, chất lượng tốt, và hành động tự phát có thể duy trì lâu dài.",
  "要報": "Tóm tắt",
  "見直す_文言編集説明": "Chỉ sửa nội dung hiện tại (không dùng AI)",
  "見直す方法を選んでください": "Bạn muốn chỉnh theo cách nào?",
  "言われたことだけやる": "Chỉ làm những gì được bảo",
  "言語": "Ngôn ngữ",
  "言語_スタートショートカット": "Bạn cũng có thể đổi trong Cài đặt",
  "言語_設定が正式": "Đây là nơi chính thức để đặt ngôn ngữ hiển thị. Nút cờ ở màn hình bắt đầu cũng đổi cùng một cài đặt.",
  "言語化することで思いが現実性を持つ": "Diễn đạt thành lời giúp suy nghĩ trở nên hiện thực hơn",
  "設定": "Cài đặt",
  "設定_削除はプライバシーへ": "Xóa trong màn hình Quyền riêng tư & dữ liệu",
  "詳報": "Báo cáo đầy đủ",
  "読み取れませんでした": "Không thể đọc được",
  "誰かに話すことによって自分の中で漠然としていた夢が、どんどんリアリティを持ち、少しずつ形になり、ビジョンになっていく。これを繰り返す内にビジョンはより明確になり、とうとう的確な言葉で表現できるようになったとき、初めて明快な物語として、リアリティのある戦略として、それを人に伝達し、実際に行動に移していく事ができる。": "Khi kể cho ai đó nghe, giấc mơ vốn còn mơ hồ trong lòng bạn dần trở nên hiện thực hơn, từng chút một hình thành và trở thành một tầm nhìn. Lặp lại điều này nhiều lần, tầm nhìn ấy càng rõ ràng hơn, và khi cuối cùng bạn có thể diễn đạt nó bằng những lời chính xác, lúc đó bạn mới có thể truyền đạt nó cho người khác như một câu chuyện rõ ràng, như một chiến lược có tính thực tế, và thực sự bắt tay vào hành động.",
  "貼り付けて確認する": "Dán và kiểm tra",
  "起動時にスタート画面を表示": "Hiện màn hình bắt đầu khi khởi động",
  "躍動：おどりうごく、いきいきと活動する": "躍動: chuyển động sôi nổi, hoạt động đầy sức sống",
  "躍（ヤク）": "Dược (躍)",
  "追加": "Thêm",
  "進捗度": "Tiến độ",
  "進捗度の見方": "Cách tính tiến độ",
  "進捗度は、案件の進み具合を示す指標です。次の段階に達するたびに上がります。": "Tiến độ cho biết dự án đã tiến xa đến đâu. Mỗi khi đạt giai đoạn tiếp theo, tiến độ sẽ tăng.",
  "違うと感じたら、カードを長押しして別の枠にドラッグしてみてください": "Nếu thấy không đúng, hãy nhấn giữ thẻ và kéo sang ô khác",
  "長押しでゴールを編集": "Nhấn giữ để sửa mục tiêu",
  "長押しでテーマを編集": "Nhấn giữ để sửa chủ đề",
  "長押しで今の状況を編集": "Nhấn giữ để sửa tình hình hiện tại",
  "長押しで宣言文を編集": "Nhấn giữ để sửa tuyên bố",
  "長押しで振り返りを編集": "Nhấn giữ để sửa nhìn lại",
  "長押しで方策を見直す": "Nhấn giữ để xem lại phương án",
  "長押しで最初の一歩を見直す": "Nhấn giữ để xem lại bước đầu tiên",
  "関連ポリシー": "Chính sách liên quan",
  "項目を追加": "Thêm mục",
  "頑張れば変えられる": "Có thể thay đổi nếu cố gắng",
  "（参考）自立とは": "(Tham khảo) Tự lập là gì?",
  "＜メリット・デメリット＞": "<Ưu và nhược điểm>",
  "＜具体例＞": "<Ví dụ>",
  "＜特徴＞": "<Đặc điểm>",
};

var GLOSSARY_EN = {
  "(テーマ未設定)": "(No theme set)",
  "10%　テーマ設定済み": "10% — Theme set",
  "100%　完了": "100% — Completed",
  "20%　ゴール設定済み": "20% — Goals set",
  "30%　今の状況設定（SWOTマトリクス完成）": "30% — Current situation set (SWOT matrix complete)",
  "40%　方策決定済み": "40% — Strategy decided",
  "50%　最初の一歩設定済み": "50% — First step set",
  "60%　宣言終了": "60% — Declaration written",
  "70%　振り返り　1回実施": "70% — 1 reflection done",
  "80%　振り返り　2回実施": "80% — 2 reflections done",
  "90%　振り返り　3回以上実施": "90% — 3 or more reflections done",
  "AIが考えた10個の最初の一歩": "10 first steps from AI",
  "AIが考えた5つの方策": "5 strategies from AI",
  "AIに再度相談する": "Ask AI again",
  "AIに方策を相談する": "Ask AI for strategies",
  "AIの回答をコピーしたら、この画面に戻って\n下のボタンをタップしてください。": "Once you've copied the AI's answer, come back to this screen\nand tap the button below.",
  "AIの提案にない、独自の方策があれば書く": "Write your own strategy here if it's not among the AI's suggestions",
  "AIの提案にない、独自の最初の一歩があれば書く": "Write your own first step here if it's not among the AI's suggestions",
  "Apple プライバシーポリシー": "Apple Privacy Policy",
  "Chromeでの回答を確認してください": "Please check the answer in Chrome",
  "Chromeを開いています…": "Opening Chrome…",
  "Chromeを開き直す": "Reopen Chrome",
  "Chromeを開けませんでした": "Couldn't open Chrome",
  "Google AIによる方策提案": "Strategy suggestions via Google AI",
  "Google AIによる最初の一歩提案": "First-step suggestions via Google AI",
  "Google プライバシーポリシー": "Google Privacy Policy",
  "JSONを取り込む": "Import JSON",
  "JSONバックアップ": "JSON backup",
  "SWOTマトリクス": "SWOT Matrix",
  "iCloud同期": "iCloud Sync",
  "iCloud同期_アップロード完了": "Uploaded to iCloud",
  "iCloud同期_エラー": "Sync failed",
  "iCloud同期_エラー_マージ失敗": "Failed to apply the downloaded data.",
  "iCloud同期_エラー_不正な応答": "Received an unexpected response from iCloud.",
  "iCloud同期_エラー_容量超過": "Your data (%@ MB) exceeds the iCloud sync limit (1 MB).",
  "iCloud同期_エラー_未検出": "Couldn't find the iCloud sync feature. Please restart the app.",
  "iCloud同期_エラー_案件未読込": "Project data has not finished loading yet.",
  "iCloud同期_クラウドコピーを削除": "Delete iCloud Cloud Copy",
  "iCloud同期_クラウドコピーを削除しますか？": "Delete the iCloud copy?",
  "iCloud同期_クラウドコピー削除失敗": "Deletion failed. Check iCloud availability and try again.",
  "iCloud同期_クラウドコピー削除完了": "The iCloud copy was deleted.",
  "iCloud同期_クラウドコピー削除確認": "This removes osmJiritsu project data and its sync timestamp from iCloud KVS. It does not delete local projects.",
  "iCloud同期_ダウンロード完了": "Downloaded from iCloud",
  "iCloud同期_フッター": "A project's theme, goals, SWOT, strategy, first step, declaration, and reflections are stored in iCloud Key-Value Storage and shared between devices signed into the same iCloud account.",
  "iCloud同期_今すぐ同期": "Sync now",
  "iCloud同期_利用不可": "iCloud is not available. Please sign in to iCloud in Settings.",
  "iCloud同期_最終同期": "Last synced",
  "iCloud同期_有効化フッター": "When on, project data syncs between devices signed into the same iCloud account.",
  "iCloud同期_未同期": "Never synced",
  "iCloud同期_相対時刻_今": "Just now",
  "iCloud同期_相対時刻_分": "%lld minute(s) ago",
  "iCloud同期_相対時刻_日": "%lld day(s) ago",
  "iCloud同期_相対時刻_時間": "%lld hour(s) ago",
  "― 伊藤守「リーダーになる人ならない人」": "― Mamoru Itō, \"Rīdā ni Naru Hito, Naranai Hito\" (People Who Become Leaders, People Who Don't)",
  "❌ 本人の興味に依存するため即効性がない": "❌ Depends on personal interest, so it has no immediate effect",
  "❌ 誰にでも同じように適用することは困難": "❌ Difficult to apply the same way to everyone",
  "⭕️ モチベーションが長持ちする": "⭕️ Motivation lasts a long time",
  "「在りたい姿」と「在りたくない姿」、両方の向きから考えてみましょう。": "Let's think about it from both directions: the future you want, and the future you want to avoid.",
  "「採用済／未採用」はタップで切り替えられます。文言を直したいときは案を長押しで編集できます。": "Tap to switch between Adopted and Not adopted. Long-press a suggestion to reword it.",
  "あとで（履歴に戻る）": "Later (back to history)",
  "あなたの方策": "Your strategy",
  "あなたの最初の一歩": "Your first step",
  "お気に入りに追加": "Add to favorites",
  "お気に入り解除": "Remove from favorites",
  "ここに置く": "Drop here",
  "この分析を削除しますか？": "Delete this analysis?",
  "この振り返りを削除しますか？": "Delete this reflection?",
  "これが実現すれば十分、と言える理想の姿（充分条件）": "The ideal state that alone would be enough (a \"sufficient condition\")",
  "これだけは避けたい、という最低ライン（必要条件）": "The baseline you want to avoid no matter what (a \"necessary condition\")",
  "これって、良いこと？ 気になること？": "Is this a good thing, or something that concerns you?",
  "すべてのデータを初期化": "Reset all data",
  "すべてのデータを削除": "Delete all data",
  "その他": "More",
  "それって、自分次第で変えられる？": "Is that something you can change yourself?",
  "それでは始めましょう": "Let's get started",
  "つまり「唱って躍れる」とは「周りを引っ張って、元気に前に進める」「自分の考えを話して、みんなと共有できる」ことである。": "In other words, \"唱って躍れる\" (sing and leap) means \"to pull others along and move forward with energy,\" and \"to voice your own thinking and share it with everyone.\"",
  "できない理由だけで、どうすればできるか？がない": "Only reasons why it can't be done — never how it could be",
  "どうだった？": "How did it go?",
  "どの枠に入れますか？": "Which box does this go in?",
  "なし": "None",
  "はじめからやり直す": "Start over",
  "はじめる": "Get started",
  "まずテーマを決めよう": "First, let's decide on a theme.",
  "まとめを共有": "Share summary",
  "まわりの状況": "The situation around me",
  "もう一度Chromeを開く": "Open Chrome again",
  "もう一度試す": "Try again",
  "もう一度貼り付ける": "Paste again",
  "やっぱりやらない": "Actually, skip it",
  "アイデアを出してみる": "Start brainstorming",
  "アプリの表示言語を変更できます。": "You can change the app's display language.",
  "インポート": "Import",
  "エクスポート": "Export",
  "エクスポートする": "Export",
  "エクスポートできる分析がまだありません": "There's nothing to export yet",
  "キャンセル": "Cancel",
  "キーワード": "Keywords",
  "クリップボードが空でした。Chromeで回答をコピーしてから、もう一度貼り付けてみてください。": "The clipboard was empty. Copy the answer in Chrome, then try pasting again.",
  "ゴールと今の状況の差を無くすために、自分で考えて行動すること": "Acting on your own judgment to close the gap between a goal and the current situation",
  "周りと繋がっているか？": "Can the goal be shared?",
  "ゴールを教えてください": "Tell us your goal",
  "ゴールを考える": "Think about your goal",
  "スタートアップ画面": "Startup Screen",
  "タップで今の状況を編集": "Tap to edit the current situation",
  "タップまたは長押しで編集": "Tap or long-press to edit",
  "ダッシュボードの全項目": "All dashboard fields",
  "ダッシュボードへ": "Open dashboard",
  "テーマ": "Theme",
  "テーマとゴール（在りたい姿／在りたくない姿）を決める": "Set a theme and goals (desired / undesired state)",
  "テーマを編集": "Edit theme",
  "データ": "Data",
  "プライバシー": "Privacy",
  "プライバシー_ポリシー本文_詳細": "Full details on external transmissions, retention, and deletion.",
  "プライバシー_保存詳細": "Theme, goals, SWOT analysis, strategy, first step, declaration, reflections, project order, display language, and start-screen settings are stored in a local Hive database on this device. There is no cloud sync.",
  "プライバシー_保持削除詳細": "Stored data is retained until you delete an item or choose Delete all data. Data already sent to Google is retained and deleted under Google’s own policy and cannot be deleted from this app. Copies saved via JSON backup to other apps also cannot be deleted by this app.",
  "プライバシー_削除確認": "Delete Hive analysis history and settings, plus temporary backup files? This cannot be undone.",
  "プライバシー_外部送信": "Recipients, data, and purposes",
  "プライバシー_方策説明": "If you request strategy suggestions, your theme, desired outcome, the state you want to avoid, and complete SWOT text (strengths, weaknesses, opportunities, and threats) are sent to Google Search (AI Mode), provided by Google LLC. The purpose is to obtain reference strategy suggestions. Consent is requested for every submission. Google’s terms and privacy policy apply.",
  "プライバシー_最初の一歩説明": "If you request first-step suggestions, your theme, desired outcome, and decided strategy are sent to Google Search (AI Mode), provided by Google LLC. The purpose is to obtain reference first-step suggestions. Consent is requested for every submission. Google’s terms and privacy policy apply.",
  "プライバシー_端末保存": "Storage on your device",
  "プライバシー_関連ポリシー_詳細": "Google’s policy applies to submissions to Google Search (AI Mode). Apple’s terms may apply to App Store distribution and device backups.",
  "プライバシーとデータ": "Privacy & Data",
  "プライバシーポリシー": "Privacy Policy",
  "ヘルプ": "Help",
  "ホーム": "Home",
  "ボタン長押しで\n操作方法を確認できます": " button to see how to use it",
  "マトリクスを確認する": "View the matrix",
  "ユーザーズマニュアル": "User manual",
  "リターン": "Return",
  "一旦休む": "Take a break",
  "一見クールでカッコよく見えたりする。的を射てるし。周囲を白けさせるパワー大。口癖は「でもさ...」": "At a glance it can look cool and sharp — the point often lands. But it has a real power to drain the energy out of everyone around. The catchphrase: \"Yeah, but...\"",
  "上司や仲間にそのまま送れます。": "Ready to send to a boss or teammate as-is.",
  "上司や仲間にそのまま送れる、ひとことにしましょう。": "Make it a line you could send to a boss or teammate as-is.",
  "不安・課題に感じる": "Feels uneasy / like an issue",
  "不平、不満ばっかり": "Nothing but complaints and grievances",
  "主導権は自分にあるのだと意識すること": "Be aware that you hold the initiative",
  "今の状況": "Current situation",
  "他人から言われる前に動く": "Act before someone else tells you to",
  "休憩中": "On break",
  "作成中": "Preparing",
  "作成中_ホームで一覧": "Use Home to return to the project list",
  "例）妥協して、納得感のないまま転職すること": "e.g. Settling for a career change I'm not really satisfied with",
  "例）新しいキャリアについて": "e.g. About a new career",
  "例）自分の強みを活かして、納得感のある転職をしたい": "e.g. I want a career change that makes use of my strengths",
  "保存": "Save",
  "備考": "Notes",
  "備考を入力…": "Enter notes…",
  "元に戻すことはできません。": "This cannot be undone.",
  "全部答えられました！": "You've answered everything!",
  "共有": "Share",
  "共有_テキスト説明": "Shares as plain text (email, messaging apps, etc.). Brief is the plan summary; Full is everything on the dashboard. JSON backup is under Data on the home screen.",
  "共有_要報説明": "Short form (theme, goals, strategy, first step, declaration). Same as the post-Stage1 share summary.",
  "共有_詳報説明": "All dashboard fields (SWOT, reflections, deadline, etc.). Better for day-to-day progress sharing.",
  "共有する": "Share",
  "共有形式を選んでください": "Choose a share format",
  "内容を編集": "Edit item",
  "内発か？外発か？": "Intrinsic or extrinsic?",
  "内発と外発は対立するものではなく組み合わせもの。外発をきっかけに始めて、その内、それ自体が楽しくなる...（エンハンシング効果）。": "Intrinsic and extrinsic motivation aren't opposites — they combine. You can start out triggered by something external, and over time the activity itself becomes enjoyable... (the enhancing effect).",
  "内発的動機づけ": "Intrinsic motivation",
  "分析結果": "Analysis result",
  "初期化": "Reset",
  "初期化しました": "Reset complete",
  "初期化の説明": "This deletes all local data and settings and restores the app to its initial state. This cannot be undone.",
  "削除": "Delete",
  "削除する": "Delete",
  "動機づけマトリクス": "Motivation matrix",
  "各画面の": "On each screen, long-press the ",
  "同意してGoogleへ送信": "Agree and send to Google",
  "周囲からサポートを得る": "Get support from the people around you",
  "唱って躍れる": "唱って躍れる\nutatte odoreru",
  "唱義：人に先立って正しい道をとなえる": "唱義: to proclaim the right path ahead of others",
  "唱（ショウ）": "Shō (唱, \"sing / proclaim\")",
  "図解で画面ごとの使い方を見る": "See illustrated steps for each screen",
  "在りたい姿": "Desired outcome",
  "在りたくない姿": "The future you want to avoid",
  "報酬、評価、昇進、あるいは罰則や叱責といった「外部からの刺激」をきっかけとして行動を促すこと。": "Prompting action through \"external stimuli\" such as rewards, evaluation, promotion, or penalties and reprimands.",
  "壁打ちメモ": "Brainstorm notes",
  "外発的動機づけ": "Extrinsic motivation",
  "完了": "Done",
  "実はこれ、SWOT分析になっています。\n出来上がったマトリクスを見てみましょう。": "This has actually become a SWOT analysis.\nLet's take a look at the finished matrix.",
  "実施中": "In progress",
  "実行のステップを細かくして達成感を感じやすくすること。": "Breaking execution into small steps so a sense of accomplishment is easy to feel.",
  "宣言文": "Declaration",
  "宣言文を確認する": "Review your declaration",
  "宣言文を編集": "Edit declaration",
  "小さなくるくる": "小さなくるくる\nchiisana kurukuru",
  "履歴に戻る": "Back to history",
  "弱み": "Weakness",
  "強み": "Strength",
  "思いついたことを入力…": "Type what comes to mind…",
  "思いつくままに、どんどん追加しよう": "Add whatever comes to mind, one after another",
  "感じたこと、気づいたことを自由に書いてみましょう": "Write freely about what you felt or noticed",
  "戻す": "Undo",
  "戻る": "Back",
  "振り返り": "Reflection",
  "振り返りを編集": "Edit reflection",
  "振り返り回数": "Reflection count",
  "振り返り履歴": "Reflection history",
  "採用済": "Adopted",
  "操作マニュアル": "User manual",
  "操作方法": "How to use",
  "操作方法_ダッシュボード": "1️⃣ View / open: tap ▶︎\n2️⃣ Delete a project: tap 🗑️ or swipe left\n3️⃣ Edit the theme: tap 🖊️\n4️⃣ Add to favorites: tap ☆\n5️⃣ Add new: tap ＋",
  "操作方法_宣言": "1️⃣ Edit: tap the item",
  "操作方法_方策最初の一歩": "1️⃣ Edit: long-press the item",
  "文言を編集": "Edit wording",
  "新しいテーマに取り組む": "Work on a new theme",
  "新規追加": "New",
  "方策": "Strategy",
  "方策の粒度を細かくすること": "Break the strategy into smaller steps",
  "方策や行動を決めるとき、この3つを満たしているか振り返ってみましょう。": "When deciding on a strategy or action, check whether it satisfies all three of these.",
  "方策を取り消しますか？": "Discard this strategy?",
  "方策を変更する": "Change strategy",
  "方策を決めた": "Strategy decided",
  "方策を決める": "Decide your strategy",
  "方策を編集": "Edit strategy",
  "方策を編集する": "Edit the strategy",
  "方策を考える際、動機づけマトリクスを意識すると良い。": "When thinking through a strategy, it helps to keep the motivation matrix in mind.",
  "方策を見直す": "Review strategy",
  "方策を読み取れませんでした。Chromeの回答全体をコピーしてから、もう一度貼り付けてみてください。": "Couldn't read the strategies. Copy the whole answer from Chrome, then try pasting again.",
  "昌には、盛んで明るいとか、美しいことばという意味があり、それと口にすることから、唱は、うたう、となえるの意味を表す。また、昌の音は、高く上げるという意味を含むから、唱は、声を高くあげること、あるいは、「人より先に大声を上げてリードする」ことである。": "昌 carries the sense of \"thriving and bright\" or \"beautiful words,\" and combined with 口 (\"mouth,\" to speak), 唱 comes to mean \"to sing\" or \"to proclaim.\" The sound 昌 also carries the nuance of \"raising something high,\" so 唱 means \"to raise one's voice\" — or \"to lead by being the first to speak up loudly.\"",
  "最初の一歩": "First step",
  "最初の一歩を取り消しますか？": "Discard this first step?",
  "最初の一歩を宣言し、振り返りながら進める": "Declare your first step, then keep going with reflection",
  "最初の一歩を決めた": "First step decided",
  "最初の一歩を決める": "Decide your first step",
  "最初の一歩を編集": "Edit first step",
  "最初の一歩を編集する": "Edit the first step",
  "最初の一歩を見直す": "Review first step",
  "最初の一歩を読み取れませんでした。Chromeの回答全体をコピーしてから、もう一度貼り付けてみてください。": "Couldn't read the first steps. Copy the whole answer from Chrome, then try pasting again.",
  "最終更新日": "Last updated",
  "期限": "Deadline",
  "期限を設定": "Set deadline",
  "未採用": "Not adopted",
  "未設定": "Not set",
  "本当に初期化しますか？": "Reset everything?",
  "案件があっても、起動時はスタート画面から始めます。": "Always start from the start screen at launch, even if you have projects.",
  "案内に従って操作": "Follow the on-screen guidance",
  "機会": "Opportunity",
  "次はどうする？": "What next?",
  "次回から表示しない": "Don't show again",
  "気になること": "A concern",
  "決めた方策を、3つの要素から見直してみましょう。": "Let's review your decided strategy against the three elements.",
  "決定": "Fix it",
  "無感動、無関心": "Indifferent, uninterested",
  "現況を変更": "Change status",
  "現状を整理し、SWOTから方策を自分で決める": "Organize the present, then decide your own strategy from SWOT",
  "環境や他人に左右される": "Affected by circumstances or others",
  "登録日": "Registered",
  "短い形式（テーマ・ゴール・方策・最初の一歩・宣言文）": "Short format (theme, goals, strategy, first step, declaration)",
  "端末内のアプリデータを削除しました": "On-device app data deleted",
  "納得した": "I'm satisfied",
  "純粋に人を喜ばせたくて仕事に取り組む。": "Taking on work purely because you want to make someone happy.",
  "成果が分かりやすいか？": "Is the outcome easy to see?",
  "結果を見える化して視覚的に成果を実感すること": "Make the results visible so progress feels real",
  "続ける": "Continue",
  "編集": "Edit",
  "翟には高く抜き出る意味がある。躍は「すばやくおどりあがる」ことである。": "翟 carries the sense of \"standing out, rising high.\" 躍 means \"to leap up quickly.\"",
  "脅威": "Threat",
  "自信がある・嬉しい": "Confident / glad",
  "自分で決められるか？": "Can you decide it yourself?",
  "自分の内面的な興味・関心、探究心、楽しさなどが原動力となる状態。": "A state driven by your own inner interest, curiosity, or enjoyment.",
  "自分以外の何ものにも依存しない状態。": "A state of depending on nothing and no one but yourself.",
  "自分次第": "Up to me",
  "自律できていない人にありがちな行動": "Behaviors common in people who lack autonomy",
  "自律とは": "What is Jiritsu?",
  "自律とは、ゴールと今の状況の差を無くすために、自分で考えて行動することです。": "Jiritsu means acting on your own judgment to close the gap between your goal and your current situation.",
  "自律の3要素": "The 3 elements of Jiritsu",
  "自律の定義": "Definition of Jiritsu",
  "内発度をチェックする": "Check your Jiritsu",
  "内発度チェック": "Jiritsu check",
  "自律計画ができました": "Your Jiritsu plan is ready",
  "自立できていない、依存している人は、自分のうまく行かない状態の責任や自分の感情、思考の原因すら周りの人や環境のせいにする。": "Someone who lacks self-reliance and depends on others blames the people and environment around them — even for their own setbacks, feelings, and thoughts.",
  "自立には経済的自立、行動的自立、精神的自立があり、いずれも自律と密接に関係している（自律している人は自立できる）。": "Self-reliance has three forms — financial, behavioral, and mental — and all three are closely tied to Jiritsu (autonomy): someone who is autonomous can become self-reliant.",
  "興味のある分野について自主的に深く調べる。": "Digging deep into a field you're interested in on your own initiative.",
  "良いこと": "Good thing",
  "行動すること自体が目的となるため、高い集中力が発揮され、質が高く、自発的な行動を長く続けやすい。": "Because the action itself becomes the goal, it brings high concentration and quality, and self-driven behavior is easy to sustain.",
  "要報": "Brief summary",
  "見直す_文言編集説明": "Edit the current text only (no AI)",
  "見直す方法を選んでください": "How do you want to revise?",
  "言われたことだけやる": "Only doing what they're told",
  "言語": "Language",
  "言語_スタートショートカット": "You can also change this in Settings",
  "言語_設定が正式": "This is the canonical place to set the display language. The flag on the start screen switches the same setting.",
  "言語化することで思いが現実性を持つ": "Putting it into words makes it feel real",
  "設定": "Settings",
  "設定_削除はプライバシーへ": "Delete from the Privacy & Data screen",
  "詳報": "Full report",
  "読み取れませんでした": "Couldn't read it",
  "誰かに話すことによって自分の中で漠然としていた夢が、どんどんリアリティを持ち、少しずつ形になり、ビジョンになっていく。これを繰り返す内にビジョンはより明確になり、とうとう的確な言葉で表現できるようになったとき、初めて明快な物語として、リアリティのある戦略として、それを人に伝達し、実際に行動に移していく事ができる。": "By telling someone else, a dream that was once vague inside you steadily gains reality, gradually takes shape, and becomes a vision. Repeat this enough times and the vision grows clearer, until at last you can put it into precise words — only then can you convey it to others as a clear story, as a strategy with real substance, and actually put it into action.",
  "貼り付けて確認する": "Paste and check",
  "起動時にスタート画面を表示": "Show start screen at launch",
  "躍動：おどりうごく、いきいきと活動する": "躍動: to move dynamically, to be vibrantly active",
  "躍（ヤク）": "Yaku (躍, \"leap\")",
  "追加": "Add",
  "進捗度": "Progress",
  "進捗度の見方": "How progress is calculated",
  "進捗度は、案件の進み具合を示す指標です。次の段階に達するたびに上がります。": "Progress shows how far a project has advanced. It increases each time you reach the next stage.",
  "違うと感じたら、カードを長押しして別の枠にドラッグしてみてください": "If something feels off, long-press a card and drag it to a different box",
  "長押しでゴールを編集": "Long-press to edit the goals",
  "長押しでテーマを編集": "Long-press to edit the theme",
  "長押しで今の状況を編集": "Long-press to edit current situation",
  "長押しで宣言文を編集": "Long-press to edit declaration",
  "長押しで振り返りを編集": "Long-press to edit reflection",
  "長押しで方策を見直す": "Long-press to review strategy",
  "長押しで最初の一歩を見直す": "Long-press to review first step",
  "関連ポリシー": "Related Policies",
  "項目を追加": "Add item",
  "頑張れば変えられる": "Can change it if I try",
  "（参考）自立とは": "(Reference) What is self-reliance?",
  "＜メリット・デメリット＞": "<Pros and cons>",
  "＜具体例＞": "<Examples>",
  "＜特徴＞": "<Characteristics>",
};
